name: Build the flutter version of the RustDesk

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: "nightly"

env:
  RUST_VERSION: "1.75"
  CARGO_NDK_VERSION: "3.1.2"
  FLUTTER_VERSION: "3.24.5"
  ANDROID_FLUTTER_VERSION: "3.24.5"
  TAG_NAME: "${{ inputs.upload-tag }}"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VERSION: "1.4.6"
  NDK_VERSION: "r28c"
  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-rustdesk-android:
    needs: [generate-bridge]
    name: build rustdesk android apk ${{ matrix.arch }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            target: aarch64-linux-android
            android_target: arm64-v8a
            flutter_target: android-arm64
            abi: arm64-v8a
          - arch: armv7
            target: armv7-linux-androideabi
            android_target: armeabi-v7a
            flutter_target: android-arm
            abi: armeabi-v7a

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
               clang \
               cmake \
               curl \
               gcc-multilib \
               git \
               g++-multilib \
               libc6-dev \
               libclang-dev \
               libunwind-dev \
               llvm-dev \
               nasm \
               ninja-build \
               openjdk-17-jdk-headless \
               pkg-config \
               wget

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.ANDROID_FLUTTER_VERSION }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: /opt/artifacts/vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          add-to-path: true

      - name: Install vcpkg dependencies
        run: ./flutter/build_android_deps.sh "${{ matrix.android_target }}"

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rustdesk-lib-cache-android
          key: ${{ matrix.target }}

      - name: Build rustdesk lib
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          rustup target add ${{ matrix.target }}
          cargo install cargo-ndk --version ${{ env.CARGO_NDK_VERSION }} --locked
          
          mkdir -p ./flutter/android/app/src/main/jniLibs/${{ matrix.abi }}
          
          if [ "${{ matrix.arch }}" = "aarch64" ]; then
            ./flutter/ndk_arm64.sh
          elif [ "${{ matrix.arch }}" = "armv7" ]; then
            ./flutter/ndk_arm.sh
          fi
          
          cp ./target/${{ matrix.target }}/release/liblibrustdesk.so ./flutter/android/app/src/main/jniLibs/${{ matrix.abi }}/librustdesk.so
          cp ${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/${{ matrix.target }}/libc++_shared.so ./flutter/android/app/src/main/jniLibs/${{ matrix.abi }}/

      - name: Build rustdesk apk
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        run: |
          export PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH
          sed -i "s/org.gradle.jvmargs=-Xmx1024M/org.gradle.jvmargs=-Xmx2g/g" ./flutter/android/gradle.properties
          sed -i "s/signingConfigs.release/signingConfigs.debug/g" ./flutter/android/app/build.gradle
          
          pushd flutter
          flutter build apk --release --target-platform ${{ matrix.flutter_target }} --split-per-abi
          mv build/app/outputs/flutter-apk/app-${{ matrix.abi }}-release.apk ../rustdesk-${{ env.VERSION }}-${{ matrix.arch }}.apk
          popd

      - name: Upload APK to Artifacts
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@master
        with:
          name: rustdesk-${{ env.VERSION }}-${{ matrix.arch }}
          path: rustdesk-${{ env.VERSION }}-${{ matrix.arch }}.apk
